In [19]:
import pandas as pd

In [20]:
# Read vine_data.csv file
Vine_Data_to_load = "Resources/vine_data_latest.csv"
vine_df = pd.read_csv(Vine_Data_to_load)
vine_df

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
0,RDIJS7QYB6XNR,5.0,0.0,0.0,N,Y
1,R36ED1U38IELG8,5.0,0.0,0.0,N,Y
2,R1UE3RPRGCOLD,2.0,1.0,1.0,N,Y
3,R298788GS6I901,5.0,0.0,0.0,N,Y
4,RNX4EXOBBPN5,1.0,1.0,1.0,N,Y
...,...,...,...,...,...,...
4864244,R1UP8F8Y4GC3IE,4.0,0.0,1.0,N,N
4864245,R3K9ZYANG0OFJB,5.0,7.0,7.0,N,N
4864246,R17ULZ2VC0O3CG,4.0,23.0,23.0,N,N
4864247,R13AWVNEKSY9M1,5.0,5.0,5.0,N,N
4864248,R1HN7EVNEN51LR,4.0,2.0,7.0,N,N

In [21]:
#Records with total_votes>20
vine_greaterthan20 = vine_df[(vine_df["total_votes"]>=20)]
vine_greaterthan20

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
104,ROP6ITXO8K5V2,5.0,23.0,27.0,N,Y
311,R3ND1LVU7AXCVF,1.0,21.0,21.0,N,Y
356,R9I5FOLKU99RY,5.0,19.0,20.0,Y,N
424,R1QS8AOD6HX3ED,4.0,59.0,81.0,N,N
546,R3ED60RC69CCQ6,5.0,22.0,23.0,Y,N
...,...,...,...,...,...,...
4864231,R38OUW047HVFOA,5.0,64.0,93.0,N,N
4864234,RX6OVBR9HW8UT,4.0,18.0,23.0,N,N
4864240,R1LGX0XI8HMJD5,1.0,59.0,65.0,N,N
4864242,R3LS3DOYDLPFE,5.0,63.0,69.0,N,N
4864246,R17ULZ2VC0O3CG,4.0,23.0,23.0,N,N

In [22]:
vine_greaterthan20["help_votes_percent"] =vine_greaterthan20["helpful_votes"]/vine_greaterthan20["total_votes"]
vine_greaterthan20

<ipython-input-22-72407a1bf1b0>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vine_greaterthan20["help_votes_percent"] =vine_greaterthan20["helpful_votes"]/vine_greaterthan20["total_votes"]

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase,help_votes_percent
104,ROP6ITXO8K5V2,5.0,23.0,27.0,N,Y,0.851852
311,R3ND1LVU7AXCVF,1.0,21.0,21.0,N,Y,1.000000
356,R9I5FOLKU99RY,5.0,19.0,20.0,Y,N,0.950000
424,R1QS8AOD6HX3ED,4.0,59.0,81.0,N,N,0.728395
546,R3ED60RC69CCQ6,5.0,22.0,23.0,Y,N,0.956522
...,...,...,...,...,...,...,...
4864231,R38OUW047HVFOA,5.0,64.0,93.0,N,N,0.688172
4864234,RX6OVBR9HW8UT,4.0,18.0,23.0,N,N,0.782609
4864240,R1LGX0XI8HMJD5,1.0,59.0,65.0,N,N,0.907692
4864242,R3LS3DOYDLPFE,5.0,63.0,69.0,N,N,0.913043
4864246,R17ULZ2VC0O3CG,4.0,23.0,23.0,N,N,1.000000

In [23]:
# Rows where the helpful_votes/total_votes is greater than 50%
vine_votes = vine_greaterthan20[(vine_greaterthan20["help_votes_percent"]>=0.5)]
vine_votes

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase,help_votes_percent
104,ROP6ITXO8K5V2,5.0,23.0,27.0,N,Y,0.851852
311,R3ND1LVU7AXCVF,1.0,21.0,21.0,N,Y,1.000000
356,R9I5FOLKU99RY,5.0,19.0,20.0,Y,N,0.950000
424,R1QS8AOD6HX3ED,4.0,59.0,81.0,N,N,0.728395
546,R3ED60RC69CCQ6,5.0,22.0,23.0,Y,N,0.956522
...,...,...,...,...,...,...,...
4864231,R38OUW047HVFOA,5.0,64.0,93.0,N,N,0.688172
4864234,RX6OVBR9HW8UT,4.0,18.0,23.0,N,N,0.782609
4864240,R1LGX0XI8HMJD5,1.0,59.0,65.0,N,N,0.907692
4864242,R3LS3DOYDLPFE,5.0,63.0,69.0,N,N,0.913043
4864246,R17ULZ2VC0O3CG,4.0,23.0,23.0,N,N,1.000000

In [24]:
# Total number of votes where helpful_votes/total_votes is greater than 50%
vine_votes["review_id"].count()

63294

In [25]:
# Number of paid reviews
vine_paid = vine_votes[(vine_votes["vine"]=='Y')]
vine_paid["review_id"].count()

1266

In [26]:
# Number of unpaid reviews
vine_unpaid = vine_votes[(vine_votes["vine"]=='N')]
vine_unpaid["review_id"].count()

62028

In [27]:
# Number of Vine paid 5 star reviews
vine_paid_5star = vine_paid[vine_paid["star_rating"] == 5]
vine_paid_5star["review_id"].count()

432

In [29]:
# Vine 5 star paid percent
vine_5star_paid_percent = (vine_paid_5star["review_id"].count()/vine_paid["review_id"].count())*100
vine_5star_paid_percent

34.12322274881517

In [30]:
# Number of Vine Unpaid 5 Star
vine_unpaid_5star = vine_unpaid[vine_unpaid["star_rating"] == 5]
vine_unpaid_5star["review_id"].count()

29982

In [31]:
# Vine Unpaid 5 star percent
vine_5star_unpaid_percent = (vine_unpaid_5star["review_id"].count()/vine_unpaid["review_id"].count())*100
vine_5star_unpaid_percent

48.33623524859741